backend:
  name: git-gateway
  branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "_site/static/images"
public_folder: "/static/images"
collections:
  - name: "reviews" #The name of the collection and should match our posts.json file's tag
    label: "Book Reviews" #The name of the collection on the CMS itself
    folder: "reviews" #The folder that our blog posts will be loaded from and saved to
    create: true #Tells the CMS that new posts can be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" #this sets the URL for the post
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "_layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
  - name: "interviews" #The name of the collection and should match our posts.json file's tag
    label: "Author Interviews" #The name of the collection on the CMS itself
    folder: "interviews" #The folder that our blog posts will be loaded from and saved to
    create: true #Tells the CMS that new posts can be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" #this sets the URL for the post
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "_layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
  - name: "tours" #The name of the collection and should match our posts.json file's tag
    label: "Blog Tours" #The name of the collection on the CMS itself
    folder: "tours" #The folder that our blog posts will be loaded from and saved to
    create: true #Tells the CMS that new posts can be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" #this sets the URL for the post
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "_layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
  - name: "blogging" #The name of the collection and should match our posts.json file's tag
    label: "Blogging Help" #The name of the collection on the CMS itself
    folder: "blogging" #The folder that our blog posts will be loaded from and saved to
    create: true #Tells the CMS that new posts can be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" #this sets the URL for the post
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "_layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
 - name: "misc" #The name of the collection and should match our posts.json file's tag
    label: "Miscellaneous" #The name of the collection on the CMS itself
    folder: "misc" #The folder that our blog posts will be loaded from and saved to
    create: true #Tells the CMS that new posts can be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" #this sets the URL for the post
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "_layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
 - name: "tbr" #The name of the collection and should match our posts.json file's tag
    label: "TBR" #The name of the collection on the CMS itself
    folder: "tbr" #The folder that our blog posts will be loaded from and saved to
    create: true #Tells the CMS that new posts can be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" #this sets the URL for the post
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "_layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
 - name: "wrapup" #The name of the collection and should match our posts.json file's tag
    label: "Wrap Up" #The name of the collection on the CMS itself
    folder: "wrapup" #The folder that our blog posts will be loaded from and saved to
    create: true #Tells the CMS that new posts can be created
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" #this sets the URL for the post
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "_layouts/post.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "date", default: "" }
      - { label: "Post Body", name: "body", widget: "markdown" }
